// <auto-generated />
using System;
using AGILE2024_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AGILE2024_BE.Migrations
{
    [DbContext(typeof(AgileDBContext))]
    [Migration("20260422073952_product")]
    partial class product
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AGILE2024_BE.Models.ContractType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContractTypes");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SuperiorId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("SuperiorId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.EmployeeCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ContractTypeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartWorkDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("WorkPercentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeCards");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Adaptation.Adaptation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedEmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ReadyDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StateId");

                    b.ToTable("Adaptations");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Adaptation.AdaptationDoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdaptationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionDocs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AdaptationId");

                    b.ToTable("AdaptationDocs");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Adaptation.AdaptationState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AdaptationStates");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Adaptation.AdaptationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdaptationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionTask")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AdaptationId");

                    b.ToTable("AdaptationTasks");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedEmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DetailDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedEmployeeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Courses.CourseEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StateId");

                    b.ToTable("CourseEmployees");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Courses.CourseState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CourseStates");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Courses.CoursesDoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionDocs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CoursesDocs");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Courses.CoursesType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CoursesTypes");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.SuccessionPlan.LeaveType", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.SuccessionPlan.ReadyStatus", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("ReadyStatuses");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.SuccessionPlan.SuccesionSkills", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SuccessionPlanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isReady")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.HasIndex("SuccessionPlanId");

                    b.ToTable("SuccesionSkills");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.SuccessionPlan.SuccessionPlan", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReadyStatusId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isExternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("leaveDate")
                        .HasColumnType("date");

                    b.Property<Guid>("leavingPersonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("successorId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("ReadyStatusId");

                    b.HasIndex("leavingPersonId");

                    b.HasIndex("successorId");

                    b.ToTable("SuccessionPlans");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.FeedbackAnswer", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FeedbackQuestionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FeedbackRecipientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("FeedbackQuestionId");

                    b.HasIndex("FeedbackRecipientId");

                    b.ToTable("FeedbackAnswers");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.FeedbackQuestion", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FeedbackRequestId")
                        .HasColumnType("char(36)");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("FeedbackRequestId");

                    b.ToTable("FeedbackQuestions");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.FeedbackRecipient", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FeedbackRequestId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FeedbackRequestStatusId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isReadBySender")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("recievedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("sentDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("EmployeeCardId");

                    b.HasIndex("FeedbackRequestId");

                    b.HasIndex("FeedbackRequestStatusId");

                    b.ToTable("FeedbackRecipients");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.FeedbackRequest", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("EmployeeCardId");

                    b.ToTable("FeedbackRequests");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.FeedbackRequestStatus", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("FeedbackRequestStatuses");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Goal", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GoalCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GoalStatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("finishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("fullfilmentRate")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("EmployeeCardId");

                    b.HasIndex("GoalCategoryId");

                    b.HasIndex("GoalStatusId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.GoalAssignment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("EmployeeCardId");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalAssignments");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.GoalCategory", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("GoalCategory");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.GoalStatus", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("GoalStatuses");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProfilePicLink")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("SuperiorId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title_after")
                        .HasColumnType("longtext");

                    b.Property<string>("Title_before")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SuperiorId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AGILE2024_BE.Models.JobPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("JobPositions");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("JobPositionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("JobPositionId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<Guid>("ReferencedItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Recognition.PointsTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecognitionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCardId");

                    b.ToTable("PointsTransactions");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Recognition.Recognition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Odmena")
                        .HasColumnType("int");

                    b.Property<string>("Predmet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCardId");

                    b.ToTable("Recognitions");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Recognition.RecognitionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RecognitionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RecognitionId");

                    b.ToTable("RecognitionAttachment");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Recognition.RecognitionRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RecognitionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("anoPlatny")
                        .HasColumnType("int");

                    b.Property<string>("dovod")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCardId");

                    b.HasIndex("RecognitionId");

                    b.ToTable("RecognitionRecipients");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Review", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<int>("counter")
                        .HasColumnType("int");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("employeeEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("superiorEndDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("EmployeeCardId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.ReviewQuestion", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReviewRecipientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("employeeDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("isSavedEmployeeDesc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isSavedSuperiorDesc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isSentEmployeeDesc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isSentSuperiorDesc")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("superiorDescription")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("ReviewRecipientId");

                    b.ToTable("ReviewQuestions");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.ReviewRecipient", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GoalAssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("char(36)");

                    b.Property<string>("employeeDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("isSavedEmployeeDesc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isSavedSuperiorDesc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isSentEmployeeDesc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isSentSuperiorDesc")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("superiorDescription")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("GoalAssignmentId");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewRecipents");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int>("CisloDomu")
                        .HasColumnType("int");

                    b.Property<string>("CisloObjednavky")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PSC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Poznamka")
                        .HasColumnType("longtext");

                    b.Property<int>("Stav")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCardId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AnoPlatny")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("ShopCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ShopCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.ProductAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductAttachments");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.ShopCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShopCategories");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.Recipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Recipient");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SurveyType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("anoPlatny")
                        .HasColumnType("int");

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("info")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCardId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeCardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SurveyQuestionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCardId");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyQuestionId");

                    b.ToTable("SurveyAnswers");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("SurveyOptions");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyOptionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SurveyAnswerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyAnswerId");

                    b.ToTable("SurveyOptionAnswer");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("answerType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyQuestion");
                });

            modelBuilder.Entity("JobPositionOrganization", b =>
                {
                    b.Property<Guid>("JobPositionsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrganizationsId")
                        .HasColumnType("char(36)");

                    b.HasKey("JobPositionsId", "OrganizationsId");

                    b.HasIndex("OrganizationsId");

                    b.ToTable("JobPositionOrganization");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Department", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Organization", "Organization")
                        .WithMany("RelatedDepartments")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("AGILE2024_BE.Models.Department", "ParentDepartment")
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId");

                    b.HasOne("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", "Superior")
                        .WithMany()
                        .HasForeignKey("SuperiorId");

                    b.Navigation("Organization");

                    b.Navigation("ParentDepartment");

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.EmployeeCard", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.ContractType", "ContractType")
                        .WithMany()
                        .HasForeignKey("ContractTypeId");

                    b.HasOne("AGILE2024_BE.Models.Department", "Department")
                        .WithMany("EmployeeCards")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("AGILE2024_BE.Models.Level", "Level")
                        .WithMany("EmployeeCards")
                        .HasForeignKey("LevelId");

                    b.HasOne("AGILE2024_BE.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ContractType");

                    b.Navigation("Department");

                    b.Navigation("Level");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Adaptation.Adaptation", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "CreatedEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Entity.Adaptation.AdaptationState", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedEmployee");

                    b.Navigation("Employee");

                    b.Navigation("State");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Adaptation.AdaptationDoc", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Entity.Adaptation.Adaptation", "Adaptation")
                        .WithMany()
                        .HasForeignKey("AdaptationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adaptation");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Adaptation.AdaptationTask", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Entity.Adaptation.Adaptation", "Adaptation")
                        .WithMany()
                        .HasForeignKey("AdaptationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adaptation");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Courses.Course", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "CreatedEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Entity.Courses.CoursesType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedEmployee");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Courses.CourseEmployee", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Entity.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Entity.Courses.CourseState", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Employee");

                    b.Navigation("State");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.Courses.CoursesDoc", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Entity.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.SuccessionPlan.SuccesionSkills", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Entity.SuccessionPlan.SuccessionPlan", "successionPlan")
                        .WithMany()
                        .HasForeignKey("SuccessionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("successionPlan");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Entity.SuccessionPlan.SuccessionPlan", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Entity.SuccessionPlan.LeaveType", "leaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Entity.SuccessionPlan.ReadyStatus", "readyStatus")
                        .WithMany()
                        .HasForeignKey("ReadyStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "leavingPerson")
                        .WithMany()
                        .HasForeignKey("leavingPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "successor")
                        .WithMany()
                        .HasForeignKey("successorId");

                    b.Navigation("leaveType");

                    b.Navigation("leavingPerson");

                    b.Navigation("readyStatus");

                    b.Navigation("successor");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.FeedbackAnswer", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.FeedbackQuestion", "request")
                        .WithMany()
                        .HasForeignKey("FeedbackQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.FeedbackRecipient", "recipient")
                        .WithMany()
                        .HasForeignKey("FeedbackRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recipient");

                    b.Navigation("request");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.FeedbackQuestion", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.FeedbackRequest", "request")
                        .WithMany()
                        .HasForeignKey("FeedbackRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("request");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.FeedbackRecipient", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "employee")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.FeedbackRequest", "feedbackRequest")
                        .WithMany()
                        .HasForeignKey("FeedbackRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.FeedbackRequestStatus", "status")
                        .WithMany()
                        .HasForeignKey("FeedbackRequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("feedbackRequest");

                    b.Navigation("status");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.FeedbackRequest", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "sender")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sender");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Goal", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "employee")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.GoalCategory", "category")
                        .WithMany()
                        .HasForeignKey("GoalCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.GoalStatus", "status")
                        .WithMany()
                        .HasForeignKey("GoalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("employee");

                    b.Navigation("status");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.GoalAssignment", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "employee")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Goal", "goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("goal");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", "Superior")
                        .WithMany()
                        .HasForeignKey("SuperiorId");

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Level", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.JobPosition", "JobPosition")
                        .WithMany("Levels")
                        .HasForeignKey("JobPositionId");

                    b.Navigation("JobPosition");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Notification", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Organization", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Recognition.PointsTransaction", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "EmployeeCard")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeCard");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Recognition.Recognition", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "createdBy")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("createdBy");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Recognition.RecognitionAttachment", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Recognition.Recognition", "Recognition")
                        .WithMany("Attachments")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Recognition.RecognitionRecipient", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "EmployeeCard")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Recognition.Recognition", "Recognition")
                        .WithMany("Recipients")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeCard");

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Review", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "sender")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sender");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.ReviewQuestion", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.ReviewRecipient", "goalAssignment")
                        .WithMany()
                        .HasForeignKey("ReviewRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("goalAssignment");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.ReviewRecipient", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.GoalAssignment", "goalAssignment")
                        .WithMany()
                        .HasForeignKey("GoalAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Review", "review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("goalAssignment");

                    b.Navigation("review");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.Order", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "Zakaznik")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zakaznik");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.OrderItem", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Shop.Order", null)
                        .WithMany("Produkty")
                        .HasForeignKey("OrderId");

                    b.HasOne("AGILE2024_BE.Models.Shop.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.Product", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Shop.ShopCategory", "ShopCategory")
                        .WithMany()
                        .HasForeignKey("ShopCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopCategory");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.ProductAttachment", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Shop.Product", "Product")
                        .WithOne("ProductAttachment")
                        .HasForeignKey("AGILE2024_BE.Models.Shop.ProductAttachment", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.Recipient", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Survey.Survey", "Survey")
                        .WithMany("Recipients")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.Survey", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "createdBy")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("createdBy");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyAnswer", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.EmployeeCard", "user")
                        .WithMany()
                        .HasForeignKey("EmployeeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Survey.Survey", "survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Survey.SurveyQuestion", "question")
                        .WithMany()
                        .HasForeignKey("SurveyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("question");

                    b.Navigation("survey");

                    b.Navigation("user");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyOption", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Survey.SurveyQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyOptionAnswer", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Survey.SurveyAnswer", "SurveyAnswer")
                        .WithMany("selectedOptions")
                        .HasForeignKey("SurveyAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyAnswer");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyQuestion", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Survey.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("JobPositionOrganization", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.JobPosition", null)
                        .WithMany()
                        .HasForeignKey("JobPositionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AGILE2024_BE.Models.Identity.ExtendedIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Department", b =>
                {
                    b.Navigation("EmployeeCards");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.JobPosition", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Level", b =>
                {
                    b.Navigation("EmployeeCards");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Organization", b =>
                {
                    b.Navigation("RelatedDepartments");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Recognition.Recognition", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.Order", b =>
                {
                    b.Navigation("Produkty");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Shop.Product", b =>
                {
                    b.Navigation("ProductAttachment")
                        .IsRequired();
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.Survey", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyAnswer", b =>
                {
                    b.Navigation("selectedOptions");
                });

            modelBuilder.Entity("AGILE2024_BE.Models.Survey.SurveyQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
